# Generated by Django 5.2 on 2025-04-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_downloads_song_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics_file',
            field=models.FileField(blank=True, null=True, upload_to='lyrics/'),
        ),
        migrations.AddField(
            model_name='song',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
