# Generated by Django 5.2 on 2025-04-11 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
